name       : haskell-http-api-data
version    : 0.4.1.1
release    : 3
source     :
    - https://hackage.haskell.org/package/http-api-data-0.4.1.1/http-api-data-0.4.1.1.tar.gz : d0aa13e2878e4b92edf71391e775476e7d36a4b5736bd5c701373002b7a823e9
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package defines typeclasses used for converting Haskell data types to and from HTTP API data.
description: |
    This package defines typeclasses used for converting Haskell data types to and from HTTP API data.
builddeps  :
    - haskell-attoparsec-iso8601-devel
    - haskell-cabal-install
    - haskell-cookie-devel
    - haskell-http-types-devel
    - haskell-tagged-devel
    - haskell-time-compat-devel
    - haskell-unordered-containers-devel
    - haskell-uuid-types-devel
    - haskell-vector-devel
rundeps    :
    - devel:
        - haskell-attoparsec-iso8601-devel
        - haskell-cookie-devel
        - haskell-http-types-devel
        - haskell-tagged-devel
        - haskell-time-compat-devel
        - haskell-unordered-containers-devel
        - haskell-uuid-types-devel
        - haskell-vector-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
