name       : haskell-http-api-data
version    : 0.3.5
release    : 1
source     :
    - http://hackage.haskell.org/package/http-api-data-0.3.5/http-api-data-0.3.5.tar.gz : 3711ac5f97afe8e89d1f8959138de8f2b3afd8ec30f9c6f3eebbfb2caa2fbc45
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package defines typeclasses used for converting Haskell data types to and from HTTP API data.
description: |
    This package defines typeclasses used for converting Haskell data types to and from HTTP API data.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
    - haskell-time-locale-compat
    - haskell-unordered-containers
    - haskell-uri-bytestring
    - haskell-uuid-types
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
