name       : haskell-http-api-data
version    : 0.3.8.1
release    : 2
source     :
    - https://hackage.haskell.org/package/http-api-data-0.3.8.1/http-api-data-0.3.8.1.tar.gz : 6eeaba4b29a00407cb20b865825b17b8d884c26b09c5bbe7b6e673b4522106b3
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package defines typeclasses used for converting Haskell data types to and from HTTP API data.
description: |
    This package defines typeclasses used for converting Haskell data types to and from HTTP API data.
builddeps  :
    - ghc-devel
    - haskell-attoparsec-iso8601
    - haskell-cabal-install
    - haskell-http-types
    - haskell-time-locale-compat
    - haskell-unordered-containers
    - haskell-uri-bytestring
    - haskell-uuid-types
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
